; LC-3 equivalent of hello.c
;
;   int main() {
;       printf("Hello how are u, this is a messaged generated by c program\n");
;       return 0;
;   }
;
; printf with a plain string literal becomes LEA (address of the string into R0)
; + TRAP x22 (PUTS). "return 0" from main becomes TRAP x25 (HALT).

        .ORIG   x3000

        LEA     R0, MSG         ; R0 <- address of the string
        PUTS                    ; TRAP x22: print chars until the x0000 terminator
        HALT                    ; TRAP x25: stop the machine

MSG     .STRINGZ "Hello how are u, this is a messaged generated by c program\n"

        .END
